"""Fix icon_url in Platform

Revision ID: 8f925b0f6862
Revises: 9cecc67ad463
Create Date: 2025-07-14 09:35:23.242169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f925b0f6862'
down_revision: Union[str, Sequence[str], None] = '9cecc67ad463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_id'), table_name='movies')
    op.drop_table('movies')
    op.drop_index(op.f('ix_platforms_id'), table_name='platforms')
    op.drop_table('platforms')
    op.drop_table('movie_platform_links')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_platform_links',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('platform_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('link_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('movie_platform_links_movie_id_fkey')),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], name=op.f('movie_platform_links_platform_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('movie_platform_links_pkey'))
    )
    op.create_table('platforms',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('platform_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('monetization_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('stream_quality', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('platforms_pkey'))
    )
    op.create_index(op.f('ix_platforms_id'), 'platforms', ['id'], unique=False)
    op.create_table('movies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('runtime', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('poster', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pictures', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('imdb_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('rating', sa.NUMERIC(precision=3, scale=1), autoincrement=False, nullable=True),
    sa.Column('genres', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('interactions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.ENUM('movie', 'series', name='contenttype'), autoincrement=False, nullable=True),
    sa.Column('number_of_seasons', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('movies_pkey')),
    sa.UniqueConstraint('imdb_id', name=op.f('movies_imdb_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_movies_id'), 'movies', ['id'], unique=False)
    # ### end Alembic commands ###
